### ISSUE TITLE
Create a Homework Component

### ISSUE THREAD

**Issue by ashx3s** [sait-wbdv/winter-2022#18]
### User Story: Instructor
- Make a standardized component for adding homework to lesson plans

#### Definition of Done
- Component is universal
- Component handles text, links, and icons
- Component opens the homework in a new tab
- Visually Distinct on lesson plan page

#### Extra Features
- Dynamically know where link is going and showing icons for end links

**Comment by lilyx13** [comment]
Unstylized code code added [with this commit](https://github.com/sait-wbdv/winter-2022/commit/ce9aa259eebfc240efa8c79e22e0391301af6c03).

[Code Journal](https://hackmd.io/@vrWidAaORSyXk3YwJnA3tA/Byx-O682F) with notes on how the component works and some of the limitations that I ran into.

**Comment by lilyx13** [comment]
Closing because the component has been made and is in use
